### ISSUE TITLE
run int winxp  python 35

### ISSUE THREAD

**Issue by wjcroom** [YaokaiYang-assaultmaster/Python-Port-Scanner-Module#1]
def __TCP_connect(self, ip, port_number, delay, output, message):
        # Initilize the TCP socket object
        TCP_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        TCP_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
        TCP_sock.settimeout(delay)
have error message :
File "C:/Python34\PortScanner.py", line 208, in __TCP_connect
    TCP_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
AttributeError: 'module' object has no attribute 'SO_REUSEPORT'
Exception in thread Thread-4:

sugest .https://stackoverflow.com/questions/13637121/so-reuseport-is-not-defined-on-windows-7

2
down vote
accepted
You need to set SO_BROADCAST option on each socket:

s.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)
SO_REUSEPORT is not standard and usually means same thing as SO_REUSEADDR where supported.

https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t?rq=1

Windows

Windows only knows the SO_REUSEADDR option, there is no SO_REUSEPORT. Setting SO_REUSEADDR on a socket in Windows behaves like setting SO_REUSEPORT and SO_REUSEADDR on a socket in BSD, with one exception: A socket with SO_REUSEADDR can always bind to exactly the same source address and port as an already bound socket, even if the other socket did not have this option set when it was bound.

**Comment by wjcroom** [comment]
TCP_sock.sendall(str(message))
TypeError: 'str' does not support the buffer interface  

https://stackoverflow.com/questions/13274553/python-3-3-socket-typeerror
tcpCliSock.send(data.encode('utf-8'))

**Comment by YaokaiYang-assaultmaster** [comment]
@wjcroom Hello wjcroom:

I've made corresponding changes to the code. Specifically, I now initialize TCP socket for Windows platform using SO_REUSEADDR and encode the message to utf-8 before sending out. 

Could you please test it on your machine to see if it works?

Thanks a lot.

**Comment by YaokaiYang-assaultmaster** [comment]
Tested it on Windows 10 py36. No more above problems showed up.
